---
title: "final project_mayur"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r read data}
nyc<-read.csv('NYCRealEstateFullData.csv')
```

```{r examine data}
str(nyc) #fix data type of sale.date
```

```{r fix sale.date}
library(lubridate)
nyc$SALE.DATE<-ymd(nyc$SALE.DATE)    #conversion from factor to date format
nyc$sale.year<-year(nyc$SALE.DATE)   #extratcing year from sale date
nyc$sale.month<-month(nyc$SALE.DATE) #extracting months from sale date
```

```{r missing data exploration}
library(DataExplorer)
plot_missing(nyc) #100% missing values for Ease.ment, 78% missing values in apartment number (can be removed from analysis)

```

```{r split into train and test}
library(caret)
a<-createDataPartition(nyc$SALE.PRICE,p = 0.70,groups =100,list=FALSE)
train<-nyc[a,]
test<-nyc[-a,]
```

```{r simple linear regression}
mod_lm<-lm(`SALE.PRICE`~BOROUGH+`LAND.SQUARE.FEET`+`GROSS.SQUARE.FEET`+`sale.year`+`TOTAL.UNITS`+`RESIDENTIAL.UNITS`+`COMMERCIAL.UNITS`,data=train)
summary(mod_lm)
pred_lm<-predict(mod_lm,newdata=test)
rmse_lm = sqrt(mean((pred_lm-test$SALE.PRICE)^2)); rmse_lm #10728827
```

```{r linear regression model 2}
mod_lm2<-lm(`SALE.PRICE`~BOROUGH+`LAND.SQUARE.FEET`+`GROSS.SQUARE.FEET`+`sale.year`+`TOTAL.UNITS`+`RESIDENTIAL.UNITS`+`COMMERCIAL.UNITS`+BLOCK,data=train)
summary(mod_lm2)
pred_lm2<-predict(mod_lm2,newdata=remove_missing_levels(mod_lm2,test_data = test))
rmse_lm2= sqrt(mean((pred_lm2-test$SALE.PRICE)^2)); rmse_lm2 #10728541
```



```{r  a simple random forest model}
library(randomForest)
sample.5000<-sample(1:nrow(train),10000)
sample_rf<-train[sample.1000,]
mod_rf1<-randomForest(`SALE.PRICE`~BOROUGH+`LAND.SQUARE.FEET`+`GROSS.SQUARE.FEET`+`sale.year`+`TOTAL.UNITS`+`RESIDENTIAL.UNITS`+`COMMERCIAL.UNITS`+BLOCK,data=sample_rf,ntree=100)
summary(mod_rf1)
pred_rf<-predict(mod_rf1,newdata=test)
rmse_rf<-sqrt(mean((pred_rf-test$SALE.PRICE)^2)); rmse_rf #10256048
```

